<?php 
return array (
  'ymcHtmlFormElementsGroup' => './interfaces/elements_group.php',
  'ymcHtmlForm' => './interfaces/form.php',
  'ymcHtmlFormElementBase' => './interfaces/element_base.php',
  'ymcHtmlFormInputSource' => './interfaces/input_source.php',
  'ymcHtmlFormElement' => './interfaces/element.php',
  'ymcHtmlFormElementRadio' => './elements/radio.php',
  'ymcHtmlFormElementSingleSelect' => './elements/single_select.php',
  'ymcHtmlFormElementPassword' => './elements/password.php',
  'ymcHtmlFormElementEmail' => './elements/email.php',
  'ymcHtmlFormElementCheckboxArray' => './elements/checkbox_array.php',
  'ymcHtmlFormElementText' => './elements/text.php',
  'ymcHtmlFormElementButton' => './elements/button.php',
  'ymcHtmlFormInputSourceDummy' => './input_sources/dummy.php',
  'ymcHtmlFormInputSourceFilterExtension' => './input_sources/filter_extension.php',
  'ymcHtmlFormFailureNotInSet' => './failures/not_in_set.php',
  'ymcHtmlFormFailureFilter' => './failures/filter.php',
  'ymcHtmlFormFailureEmpty' => './failures/empty.php',
  'ymcHtmlFormFailure' => './failure.php',
  'ymcHtmlFormElementsGroupGeneric' => './elements_group_generic.php',
  'ymcHtmlFormDuplicateNameException' => './exceptions/duplicate_name.php',
  'ymcHtmlFormException' => './exceptions/base.php',
  'ymcHtmlFormElementOptions' => './options/element.php',
  'ymcHtmlFormGeneric' => './form_generic.php',
);
?>
